//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.emailServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class missingEmailDataBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class commonDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string exceptionCauseField;
        
        private string statusField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exceptionCause {
            get {
                return this.exceptionCauseField;
            }
            set {
                this.exceptionCauseField = value;
                this.RaisePropertyChanged("exceptionCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class emailAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] emailAttachment1Field;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailAttachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] emailAttachment1 {
            get {
                return this.emailAttachment1Field;
            }
            set {
                this.emailAttachment1Field = value;
                this.RaisePropertyChanged("emailAttachment1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class EmailRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromEmailField;
        
        private string toEmailField;
        
        private string messageField;
        
        private string subjectField;
        
        private emailAttachment[] emailAttachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
                this.RaisePropertyChanged("fromEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string toEmail {
            get {
                return this.toEmailField;
            }
            set {
                this.toEmailField = value;
                this.RaisePropertyChanged("toEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailAttachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public emailAttachment[] emailAttachments {
            get {
                return this.emailAttachmentsField;
            }
            set {
                this.emailAttachmentsField = value;
                this.RaisePropertyChanged("emailAttachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class NotValidEmailException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.soap.ws.email.dm.ae/", ConfigurationName="emailServiceReference.emailService")]
    public interface emailService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ModificationHousingFeesAdmin.emailServiceReference.missingEmailDataBean), Action="", Name="MissingEmailDataException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ModificationHousingFeesAdmin.emailServiceReference.NotValidEmailException), Action="", Name="NotValidEmailException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse sendEmail(ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse> sendEmailAsync(ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ModificationHousingFeesAdmin.emailServiceReference.missingEmailDataBean), Action="", Name="MissingEmailDataException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ModificationHousingFeesAdmin.emailServiceReference.NotValidEmailException), Action="", Name="NotValidEmailException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse sendEmailToMultipleRecipients(ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse> sendEmailToMultipleRecipientsAsync(ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEmail", WrapperNamespace="http://service.soap.ws.email.dm.ae/", IsWrapped=true)]
    public partial class sendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.ws.email.dm.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModificationHousingFeesAdmin.emailServiceReference.EmailRequestType emailRequest;
        
        public sendEmailRequest() {
        }
        
        public sendEmailRequest(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestType emailRequest) {
            this.emailRequest = emailRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEmailResponse", WrapperNamespace="http://service.soap.ws.email.dm.ae/", IsWrapped=true)]
    public partial class sendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.ws.email.dm.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModificationHousingFeesAdmin.emailServiceReference.commonDTO @return;
        
        public sendEmailResponse() {
        }
        
        public sendEmailResponse(ModificationHousingFeesAdmin.emailServiceReference.commonDTO @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.ws.email.dm.ae/")]
    public partial class EmailRequestMultipleRecipients : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromEmailField;
        
        private string[] recipientsEmailsField;
        
        private string messageField;
        
        private string subjectField;
        
        private emailAttachment[] emailAttachmentsField;
        
        private string[] ccEmailsField;
        
        private string[] bccEmailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
                this.RaisePropertyChanged("fromEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipientsEmails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] recipientsEmails {
            get {
                return this.recipientsEmailsField;
            }
            set {
                this.recipientsEmailsField = value;
                this.RaisePropertyChanged("recipientsEmails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailAttachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public emailAttachment[] emailAttachments {
            get {
                return this.emailAttachmentsField;
            }
            set {
                this.emailAttachmentsField = value;
                this.RaisePropertyChanged("emailAttachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ccEmails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string[] ccEmails {
            get {
                return this.ccEmailsField;
            }
            set {
                this.ccEmailsField = value;
                this.RaisePropertyChanged("ccEmails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bccEmails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string[] bccEmails {
            get {
                return this.bccEmailsField;
            }
            set {
                this.bccEmailsField = value;
                this.RaisePropertyChanged("bccEmails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEmailToMultipleRecipients", WrapperNamespace="http://service.soap.ws.email.dm.ae/", IsWrapped=true)]
    public partial class sendEmailToMultipleRecipientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.ws.email.dm.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModificationHousingFeesAdmin.emailServiceReference.EmailRequestMultipleRecipients EmailRequestMultipleRecipients;
        
        public sendEmailToMultipleRecipientsRequest() {
        }
        
        public sendEmailToMultipleRecipientsRequest(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestMultipleRecipients EmailRequestMultipleRecipients) {
            this.EmailRequestMultipleRecipients = EmailRequestMultipleRecipients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEmailToMultipleRecipientsResponse", WrapperNamespace="http://service.soap.ws.email.dm.ae/", IsWrapped=true)]
    public partial class sendEmailToMultipleRecipientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.ws.email.dm.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModificationHousingFeesAdmin.emailServiceReference.commonDTO @return;
        
        public sendEmailToMultipleRecipientsResponse() {
        }
        
        public sendEmailToMultipleRecipientsResponse(ModificationHousingFeesAdmin.emailServiceReference.commonDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface emailServiceChannel : ModificationHousingFeesAdmin.emailServiceReference.emailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class emailServiceClient : System.ServiceModel.ClientBase<ModificationHousingFeesAdmin.emailServiceReference.emailService>, ModificationHousingFeesAdmin.emailServiceReference.emailService {
        
        public emailServiceClient() {
        }
        
        public emailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public emailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public emailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public emailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse ModificationHousingFeesAdmin.emailServiceReference.emailService.sendEmail(ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest request) {
            return base.Channel.sendEmail(request);
        }
        
        public ModificationHousingFeesAdmin.emailServiceReference.commonDTO sendEmail(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestType emailRequest) {
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest inValue = new ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest();
            inValue.emailRequest = emailRequest;
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse retVal = ((ModificationHousingFeesAdmin.emailServiceReference.emailService)(this)).sendEmail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse> ModificationHousingFeesAdmin.emailServiceReference.emailService.sendEmailAsync(ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest request) {
            return base.Channel.sendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailResponse> sendEmailAsync(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestType emailRequest) {
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest inValue = new ModificationHousingFeesAdmin.emailServiceReference.sendEmailRequest();
            inValue.emailRequest = emailRequest;
            return ((ModificationHousingFeesAdmin.emailServiceReference.emailService)(this)).sendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse ModificationHousingFeesAdmin.emailServiceReference.emailService.sendEmailToMultipleRecipients(ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest request) {
            return base.Channel.sendEmailToMultipleRecipients(request);
        }
        
        public ModificationHousingFeesAdmin.emailServiceReference.commonDTO sendEmailToMultipleRecipients(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestMultipleRecipients EmailRequestMultipleRecipients) {
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest inValue = new ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest();
            inValue.EmailRequestMultipleRecipients = EmailRequestMultipleRecipients;
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse retVal = ((ModificationHousingFeesAdmin.emailServiceReference.emailService)(this)).sendEmailToMultipleRecipients(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse> ModificationHousingFeesAdmin.emailServiceReference.emailService.sendEmailToMultipleRecipientsAsync(ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest request) {
            return base.Channel.sendEmailToMultipleRecipientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsResponse> sendEmailToMultipleRecipientsAsync(ModificationHousingFeesAdmin.emailServiceReference.EmailRequestMultipleRecipients EmailRequestMultipleRecipients) {
            ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest inValue = new ModificationHousingFeesAdmin.emailServiceReference.sendEmailToMultipleRecipientsRequest();
            inValue.EmailRequestMultipleRecipients = EmailRequestMultipleRecipients;
            return ((ModificationHousingFeesAdmin.emailServiceReference.emailService)(this)).sendEmailToMultipleRecipientsAsync(inValue);
        }
    }
}
