//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_CommunitiesPlaces
    {
        public int Id { get; set; }
        public int Area_Id { get; set; }
        public int Community_Id { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual Community_Places Community_Places { get; set; }
        public virtual Area Area { get; set; }
    }
}
