//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModificationHousingFeesEntities : DbContext
    {
        public ModificationHousingFeesEntities()
            : base("name=ModificationHousingFeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area_CommunitiesPlaces> Area_CommunitiesPlaces { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Community_Places> Community_Places { get; set; }
        public virtual DbSet<property_Areas> property_Areas { get; set; }
        public virtual DbSet<Property_Types> Property_Types { get; set; }
        public virtual DbSet<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<HousingFeesExceptionLog> HousingFeesExceptionLogs { get; set; }
    }
}
