//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property_Types()
        {
            this.property_Areas = new HashSet<property_Areas>();
            this.Request_Modify_DM_Housing_Fees = new HashSet<Request_Modify_DM_Housing_Fees>();
        }
    
        public int Id { get; set; }
        public string Arabic_Name { get; set; }
        public string English_Name { get; set; }
        public string Created_By { get; set; }
        public string Updated_By { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_Areas> property_Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees { get; set; }
    }
}
