//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Modify_DM_Housing_Fees
    {
        public int Id { get; set; }
        public string RequestorType { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public string EmailAddress { get; set; }
        public string PropertyType { get; set; }
        public string PremiseNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Remarks { get; set; }
        public string MakaniNumber { get; set; }
        public string Xcoordinator { get; set; }
        public string Ycoordinator { get; set; }
        public string PlotNumber { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string BuildingNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string PointOfSample { get; set; }
        public byte[] CopyOfDewaBill { get; set; }
        public string MimeTypeCopyOfDewaBill { get; set; }
        public byte[] LetterFromOwnerMentioningMeters { get; set; }
        public string MimeTypeLetterFromOwnerMentioningMeters { get; set; }
        public byte[] CopyOfEjariCertificate { get; set; }
        public string MimeTypeCopyOfEjariCertificate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Status { get; set; }
        public byte[] TitleDeed { get; set; }
        public string MimeTypeTitleDeed { get; set; }
        public byte[] LayoutAttachmentBinary { get; set; }
        public string MimeTypeLayout { get; set; }
        public string RejectionReason { get; set; }
        public string Employee_Comment { get; set; }
        public Nullable<int> Approved_Review_By_User_Id { get; set; }
        public Nullable<int> Rejected_By_User_Id { get; set; }
        public Nullable<int> Locked_By_User_Id { get; set; }
        public Nullable<int> Approved_Manual_Update_By_User_Id { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> communityPlaceId { get; set; }
        public string lang { get; set; }
        public string CopyOfDewaBill_FileName { get; set; }
        public string LetterFromOwnerMentioningMeters_FileName { get; set; }
        public string CopyOfEjariCertificate_FileName { get; set; }
        public string TitleDeed_FileName { get; set; }
        public string LayoutAttachment_FileName { get; set; }
        public string OwnerName { get; set; }
        public string EjariNumber { get; set; }
        public string ContractAddress { get; set; }
        public string ContractEndDate { get; set; }
        public string EjariRegisteredBy { get; set; }
        public string HousingFees { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Community_Places Community_Places { get; set; }
        public virtual Property_Types Property_Types { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
