//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Request_Modify_DM_Housing_Fees = new HashSet<Request_Modify_DM_Housing_Fees>();
            this.Request_Modify_DM_Housing_Fees1 = new HashSet<Request_Modify_DM_Housing_Fees>();
            this.Request_Modify_DM_Housing_Fees2 = new HashSet<Request_Modify_DM_Housing_Fees>();
            this.Request_Modify_DM_Housing_Fees3 = new HashSet<Request_Modify_DM_Housing_Fees>();
        }
    
        public int id { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ARABIC { get; set; }
        public string NAME_ENGLISH { get; set; }
        public string EMAIL { get; set; }
        public bool Has_Review_Role { get; set; }
        public bool Has_Manul_Update_Role_In_Dewa { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public bool Has_Admin_Role { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Modify_DM_Housing_Fees> Request_Modify_DM_Housing_Fees3 { get; set; }
    }
}
