//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModificationHousingFeesAdmin.smsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBrokerService/v1", ConfigurationName="smsServiceReference.DmSmsBrokerServicePT")]
    public interface DmSmsBrokerServicePT {
        
        // CODEGEN: Generating message contract since the operation sendMultipleSMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dm.gov.ae/dmsmg/DmSmsBrokerService/v1/sendMultipleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse sendMultipleSMS(ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dm.gov.ae/dmsmg/DmSmsBrokerService/v1/sendMultipleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse> sendMultipleSMSAsync(ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class DmSmsBrokerRequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string messageField;
        
        private string[] recipientsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] Recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("Recipients");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class PropertyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class CodedValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class SMSResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recipientField;
        
        private CodedValue statusCodeField;
        
        private PropertyType[] extensionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("Recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public CodedValue StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PropertyType[] Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("Extensions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class SMSAcknowledgementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SMSResponseType[] sMSResponseListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SMSResponseType[] SMSResponseList {
            get {
                return this.sMSResponseListField;
            }
            set {
                this.sMSResponseListField = value;
                this.RaisePropertyChanged("SMSResponseList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBroker/v1")]
    public partial class DmSmsBrokerPesponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string messageField;
        
        private SMSAcknowledgementType sMSAcknowledgementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SMSAcknowledgementType SMSAcknowledgement {
            get {
                return this.sMSAcknowledgementField;
            }
            set {
                this.sMSAcknowledgementField = value;
                this.RaisePropertyChanged("SMSAcknowledgement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultipleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBrokerService/v1", Order=0)]
        public ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerRequestMessage DmSmsBrokerRequest;
        
        public sendMultipleSMSRequest() {
        }
        
        public sendMultipleSMSRequest(ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerRequestMessage DmSmsBrokerRequest) {
            this.DmSmsBrokerRequest = DmSmsBrokerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultipleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dm.gov.ae/dmsmg/DmSmsBrokerService/v1", Order=0)]
        public ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerPesponseMessage DmSmsBrokerPesponse;
        
        public sendMultipleSMSResponse() {
        }
        
        public sendMultipleSMSResponse(ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerPesponseMessage DmSmsBrokerPesponse) {
            this.DmSmsBrokerPesponse = DmSmsBrokerPesponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DmSmsBrokerServicePTChannel : ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmSmsBrokerServicePTClient : System.ServiceModel.ClientBase<ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT>, ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT {
        
        public DmSmsBrokerServicePTClient() {
        }
        
        public DmSmsBrokerServicePTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmSmsBrokerServicePTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmSmsBrokerServicePTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmSmsBrokerServicePTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT.sendMultipleSMS(ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest request) {
            return base.Channel.sendMultipleSMS(request);
        }
        
        public ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerPesponseMessage sendMultipleSMS(ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerRequestMessage DmSmsBrokerRequest) {
            ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest inValue = new ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest();
            inValue.DmSmsBrokerRequest = DmSmsBrokerRequest;
            ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse retVal = ((ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT)(this)).sendMultipleSMS(inValue);
            return retVal.DmSmsBrokerPesponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse> ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT.sendMultipleSMSAsync(ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest request) {
            return base.Channel.sendMultipleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSResponse> sendMultipleSMSAsync(ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerRequestMessage DmSmsBrokerRequest) {
            ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest inValue = new ModificationHousingFeesAdmin.smsServiceReference.sendMultipleSMSRequest();
            inValue.DmSmsBrokerRequest = DmSmsBrokerRequest;
            return ((ModificationHousingFeesAdmin.smsServiceReference.DmSmsBrokerServicePT)(this)).sendMultipleSMSAsync(inValue);
        }
    }
}
